 # default: &default
 #  adapter: postgresql
 #  encoding: unicode
 #  # For details on connection pooling, see Rails configuration guide
 #  # http://guides.rubyonrails.org/configuring.html#database-pooling
 #  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

 # development:
 #   adapter: postgresql
 #   database: db/development
 #   database: dev
 #   pool: 5
 #   timeout: 5000
   
 # test:
 #   adapter: postgresql
 #   database: db/test
 #   database: test
 #   pool: 5
 #   timeout: 5000
   
 # production:
 #   adapter: postgresql
 #   database: db/production
 #   database: production
 #   pool: 5
 #   timeout: 5000
 
 # SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>