 development:
   adapter: postgresql
   database: db/development
   database: dev
   pool: 5
   timeout: 5000
   
 test:
   adapter: postgresql
   database: db/test
   database: test
   pool: 5
   timeout: 5000
   
 production:
   adapter: postgresql
   database: db/production
   database: production
   pool: 5
   timeout: 5000