# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d5a6357d900d2f64a7d24eb86cd90c39785b6ec5e14a201ce769366f820a2109c91d19c805296822fcf590eb9912f24e7b49d126661cbdb0f49eaba7ec0890a

test:
  secret_key_base: ef54124d6b3d74476de789c5a4ae1eabe83b118991c7b6352488826d6c89ee036f69767c7f8a503d7226282cce92544d94fc6e86a07efd3aac0068fbce36e30e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
